#!/usr/bin/env bash
# setup ufw to allow ssh, http and https while blocking all the other traffic

sudo apt install ufw
sudo ufw disable
sudo ufw --force reset
sudo ufw defaut deny incoming
sudo ufw default allow outgoing
sudo systemctl stop ufw
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo systemctl start ufw
sudo ufw --force enable
apt-get -y update
apt -y install ufw

#modifying config file to accept IPv6 connections
sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw

# setting up default policies
ufw default deny incoming
ufw default allow outgoing

# allowing ssh, http and https connections
ufw allow ssh
ufw allow http
ufw allow https

echo 'y' | sudo ufw enable
